tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'surface-tint': '#006c4a',
        'secondary-container': '#dae2fd',
        'tertiary-fixed': '#ffdada',
        'on-secondary-container': '#5c647a',
        'on-primary-fixed-variant': '#005137',
        'on-surface': '#0b1c30',
        'primary-container': '#00855d',
        'on-secondary-fixed': '#131b2e',
        'surface-container-highest': '#d3e4fe',
        'surface-container-high': '#dce9ff',
        'surface-container': '#e5eeff',
        'on-tertiary-fixed': '#40000c',
        'on-primary-container': '#f5fff7',
        'on-primary-fixed': '#002114',
        'on-tertiary-fixed-variant': '#920028',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#3d4a42',
        'tertiary-container': '#e21e49',
        'primary': '#006948',
        'on-tertiary': '#ffffff',
        'on-background': '#0b1c30',
        'outline-variant': '#bccac0',
        'surface-container-low': '#eff4ff',
        'on-tertiary-container': '#fffbff',
        'error-container': '#ffdad6',
        'surface': '#f8f9ff',
        'secondary': '#565e74',
        'on-error': '#ffffff',
        'outline': '#6d7a72',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed-dim': '#ffb3b6',
        'secondary-fixed-dim': '#bec6e0',
        'tertiary': '#ba0035',
        'background': '#f8f9ff',
        'inverse-on-surface': '#eaf1ff',
        'surface-dim': '#cbdbf5',
        'on-secondary': '#ffffff',
        'primary-fixed': '#85f8c4',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#68dba9',
        'secondary-fixed': '#dae2fd',
        'inverse-primary': '#68dba9',
        'on-secondary-fixed-variant': '#3f465c',
        'inverse-surface': '#213145',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff'
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xs": "0.25rem",
        "margin": "1.25rem",
        "space-xl": "1.75rem",
        "space-sm": "0.5rem",
        "space-lg": "1.25rem",
        "space-md": "0.75rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "currency-display": ["Space Grotesk", "sans-serif"],
        "label-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "sans": ["Hanken Grotesk", "sans-serif"],
        "display": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "currency-display": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    }
  }
};
